[project]
name = "awareness-daemon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gespel", email = "sten.heimbrodt@hotmail.de" }
]
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.3",
    "psycopg2-binary>=2.9.0",
]

[project.scripts]
awareness-daemon = "awareness_daemon:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
